#!/usr/bin/env bash
#
# Cloud dev-sandbox bootstrap for "Claude Code on the web".
#
# The cloud environment's "Setup script" field should contain a single line:
#
#     bash scripts/cloud-setup.sh
#
# Keeping the heavy logic here (instead of pasted into the cloud UI) makes it
# version-controlled and shared with the team. The script runs as root, before
# the Claude Code session starts, and its result is cached for ~7 days, so the
# expensive installs only happen on the first session in a fresh environment.
#
# Goal: reproduce the local dev experience (backend + frontend + Firestore
# emulator) without any secrets. Live OpenAI calls require adding OPENAI_API_KEY
# to the cloud "Environment variables" field; everything else works without it
# because FLASK_ENV=development downgrades the missing-secret fail-fast to a warn.
#
# The system-mutating steps (apt, global npm, --break-system-packages) are
# guarded so an accidental local run is non-destructive.

set -euo pipefail
cd "$(dirname "$0")/.."   # repo root, regardless of where this is invoked from

echo "==> Lingual cloud dev setup"

is_root() { [ "$(id -u)" = "0" ]; }

# 1. Java — required by the Firestore emulator. The cloud base image ships
#    Python/Node/Docker/Postgres/Redis but no JRE.
if command -v java >/dev/null 2>&1; then
  echo "--> java already present, skipping JRE install"
elif is_root && command -v apt-get >/dev/null 2>&1; then
  echo "--> installing default-jre-headless for the Firestore emulator"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y --no-install-recommends default-jre-headless
else
  echo "!!! java missing and cannot apt-get install (not root) — emulator tests will not run" >&2
fi

# 2. Backend Python deps. Ubuntu 24.04 marks system Python as externally-managed
#    (PEP 668), so a root install needs --break-system-packages. We install to the
#    system interpreter (not a venv) on purpose: the Bash tool starts a fresh shell
#    per command, so a venv would need re-activation every call — system install
#    means `python3 main.py` just works anywhere. Locals inside a venv install normally.
PIP_FLAGS=""
if [ -z "${VIRTUAL_ENV:-}" ] && is_root; then
  PIP_FLAGS="--break-system-packages"
fi
echo "--> installing backend requirements ${PIP_FLAGS}"
python3 -m pip install ${PIP_FLAGS} --upgrade pip
python3 -m pip install ${PIP_FLAGS} -r requirements.txt
# Uncomment to also run the Cloud Functions emulator:
# python3 -m pip install ${PIP_FLAGS} -r functions/requirements.txt

# 3. Frontend deps. Base Node 22 satisfies Vite 7 / React 19. Prefer the lockfile.
echo "--> installing frontend deps"
( cd frontend && (npm ci || npm install) )

# 4. Firebase CLI — provides the Firestore emulator used by `make test-emulator`.
if command -v firebase >/dev/null 2>&1; then
  echo "--> firebase CLI already present"
else
  echo "--> installing firebase-tools globally"
  npm install -g firebase-tools || echo "!!! global firebase-tools install failed (need root/npm prefix)" >&2
fi

# 5. Non-secret env defaults. main.py calls load_dotenv() at import time, so this
#    .env is read automatically. We never write GOOGLE_APPLICATION_CREDENTIALS
#    (the service-account.json is gitignored and absent in the cloud) — instead
#    FIRESTORE_EMULATOR_HOST routes the Admin SDK to the local emulator with no
#    credentials. Add real secrets via the cloud "Environment variables" field,
#    NOT here. We never clobber an existing .env (protects local developers).
if [ -f .env ]; then
  echo "--> .env already exists, leaving it untouched"
else
  echo "--> writing .env (non-secret cloud defaults)"
  cat > .env <<'EOF'
# Generated by scripts/cloud-setup.sh — non-secret cloud dev defaults.
# Add secrets (OPENAI_API_KEY, etc.) in the cloud "Environment variables" field.
FLASK_ENV=development
GOOGLE_CLOUD_PROJECT=lingu-480600
GCLOUD_PROJECT=lingu-480600
PORT=5001
# Route Firebase Admin SDK to the local Firestore emulator (no service account needed).
FIRESTORE_EMULATOR_HOST=localhost:8787
EOF
fi

echo "==> Done. Next, in a session:"
echo "    firebase emulators:start --only firestore --project lingu-480600   # start first"
echo "    python3 main.py                                                    # backend :5001"
echo "    (cd frontend && npm run dev)                                       # frontend :5173"
